name: Job
on:
    workflow_dispatch:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  cache: yarn
            - run: yarn install
            - run: node run.js
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    keepalive:
        runs-on: ubuntu-latest
        permissions:
            actions: write
        steps:
            - uses: actions/checkout@v4
            - uses: gautamkrishnar/keepalive-workflow@v2
